[parameters]
LATTICE = "chain lattice"
MODEL = "spin"
local_S = 1
J = 1
L = 4
CONSERVED_QUANTUMNUMBERS = "Sz"
"MEASURE_STRUCTURE_FACTOR[Structure Factor Sz]" = "Sz"
"MEASURE_CORRELATIONS[Diagonal spin correlations]" = "Sz"
"MEASURE_CORRELATIONS[Offdiagonal spin correlations]" = "Splus:Sminus"
[output]
results = "parm1a.out.h5"
