# SPDX-License-Identifier: MIT
string(RANDOM LENGTH 12 nonce)
set(work "${CMAKE_CURRENT_BINARY_DIR}/parameters-${nonce}")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/input" "BASESEED=42\nSIMULATION_NAME=\"conversion test\"\n{ L=4 }\n{ L=8; SEED=17 }\n")
foreach(format xml hdf5)
  if(format STREQUAL xml)
    set(ext xml)
    set(program "${xml_program}")
  else()
    set(ext h5)
    set(program "${hdf5_program}")
  endif()
  execute_process(COMMAND "${program}" input "${format}" "J=2"
    WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Conversion failed: ${output}\n${errors}")
  endif()
  file(READ "${work}/${format}.in.xml" job)
  foreach(expected "name=\"conversion test\"" "${format}.out.${ext}" "${format}.task1.in.${ext}" "${format}.task2.out.${ext}")
    string(FIND "${job}" "${expected}" found)
    if(found EQUAL -1)
      message(FATAL_ERROR "Missing ${expected}: ${job}")
    endif()
  endforeach()
  foreach(task 1 2)
    if(NOT EXISTS "${work}/${format}.task${task}.in.${ext}")
      message(FATAL_ERROR "Missing converted task ${task}")
    endif()
  endforeach()
  execute_process(COMMAND "${program}" input invalid "L=100"
    WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if(status EQUAL 0 OR NOT errors MATCHES "already defined")
    message(FATAL_ERROR "Conflicting parameter override was not rejected")
  endif()
endforeach()
file(READ "${work}/xml.task1.in.xml" first)
file(READ "${work}/xml.task2.in.xml" second)
foreach(pair "SEED;42" "L;4" "J;2")
  list(GET pair 0 name)
  list(GET pair 1 value)
  if(NOT first MATCHES "name=\"${name}\">${value}</PARAMETER>")
    message(FATAL_ERROR "Wrong ${name}: ${first}")
  endif()
endforeach()
if(NOT second MATCHES "name=\"SEED\">17</PARAMETER>" OR first MATCHES "name=\"SIMULATION_NAME\"")
  message(FATAL_ERROR "Seed override or simulation-name extraction changed")
endif()
file(REMOVE_RECURSE "${work}")
