# Copyright (C) 2026 ALPS collaboration. SPDX-License-Identifier: MIT
include(CMakeFindDependencyMacro)

# The wheel owns its runtime layout; the C++ SDK only supplies its public API.
block(SCOPE_FOR VARIABLES PROPAGATE pyalps_FOUND pyalps_NOT_FOUND_MESSAGE)
  get_filename_component(package "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
  file(READ "${package}/runtime.json" metadata)
  string(JSON schema GET "${metadata}" schema)
  string(JSON version GET "${metadata}" alps_version)
  string(JSON repaired GET "${metadata}" repaired)
  find_dependency(ALPS CONFIG COMPONENTS utilities hdf5 params osiris xml cli)
  if(NOT schema EQUAL 1 OR NOT version STREQUAL ALPS_VERSION)
    set(pyalps_FOUND FALSE)
    set(pyalps_NOT_FOUND_MESSAGE "pyalps requires runtime schema 1 and ALPS SDK ${version}")
    return()
  endif()
  # nanobind types are shared only between modules with matching internals ABIs.
  # Check at configure time: a mismatch can otherwise abort Python on import.
  if(NOT NB_DIR OR NOT EXISTS "${NB_DIR}/src/nb_abi.h")
    set(pyalps_FOUND FALSE)
    set(pyalps_NOT_FOUND_MESSAGE "Call find_package(nanobind CONFIG REQUIRED) before find_package(pyalps)")
    return()
  endif()
  file(STRINGS "${NB_DIR}/src/nb_abi.h" abi_line
    REGEX "^#[ \t]*define[ \t]+NB_INTERNALS_VERSION[ \t]+[0-9]+")
  string(REGEX MATCH "[0-9]+$" consumer_abi "${abi_line}")
  string(JSON wheel_abi ERROR_VARIABLE abi_error GET "${metadata}" nanobind internals_abi)
  string(JSON wheel_nb_version ERROR_VARIABLE version_error GET "${metadata}" nanobind version)
  if(abi_error OR version_error OR NOT consumer_abi STREQUAL wheel_abi)
    set(pyalps_FOUND FALSE)
    set(pyalps_NOT_FOUND_MESSAGE
      "nanobind ${nanobind_VERSION} (internals ABI ${consumer_abi}) does not match pyalps nanobind ${wheel_nb_version} (ABI ${wheel_abi}). Install the matching nanobind release and reconfigure in a fresh build directory.")
    return()
  endif()
  if(TARGET pyalps::runtime)
    return()
  endif()
  # Windows uses stable DLL names and the matching SDK import libraries.
  if(WIN32)
    add_library(pyalps::runtime INTERFACE IMPORTED)
    target_include_directories(pyalps::runtime INTERFACE "${package}/include")
    target_link_libraries(pyalps::runtime INTERFACE ALPS::alps)
    return()
  endif()

  string(JSON count LENGTH "${metadata}" libraries)
  if(count EQUAL 0)
    set(pyalps_FOUND FALSE)
    set(pyalps_NOT_FOUND_MESSAGE "The repaired pyalps wheel contains no runtime libraries")
    return()
  endif()
  file(REAL_PATH "${package}/.." site_packages)
  math(EXPR last "${count} - 1")
  set(libraries "")
  foreach(index RANGE ${last})
    string(JSON relative GET "${metadata}" libraries ${index} path)
    file(REAL_PATH "${package}/${relative}" library)
    cmake_path(IS_PREFIX site_packages "${library}" NORMALIZE within_package)
    if(NOT within_package OR NOT EXISTS "${library}")
      set(pyalps_FOUND FALSE)
      set(pyalps_NOT_FOUND_MESSAGE "Missing or invalid pyalps runtime file: ${relative}")
      return()
    endif()
    list(APPEND libraries "${library}")
  endforeach()
  add_library(pyalps::runtime INTERFACE IMPORTED)
  target_include_directories(pyalps::runtime INTERFACE "${package}/include")
  target_link_libraries(pyalps::runtime INTERFACE ALPS::headers Threads::Threads)
  foreach(index RANGE ${last})
    list(GET libraries ${index} library)
    add_library(pyalps::library${index} SHARED IMPORTED)
    set_target_properties(pyalps::library${index} PROPERTIES IMPORTED_LOCATION "${library}")
    if(APPLE AND library MATCHES "\\.dylib$")
      string(JSON install_name GET "${metadata}" libraries ${index} install_name)
      set_target_properties(pyalps::library${index} PROPERTIES IMPORTED_SONAME "${install_name}")
    endif()
    target_link_libraries(pyalps::runtime INTERFACE pyalps::library${index})
  endforeach()
  if(NOT repaired)
    # Use package-owned copies of every ALPS runtime component. Only their
    # external dependencies come from the matching SDK in developer installs.
    set(sdk_dependencies "")
    foreach(runtime IN LISTS ALPS_RUNTIME_TARGETS)
      get_target_property(dependencies ${runtime} INTERFACE_LINK_LIBRARIES)
      if(dependencies)
        list(APPEND sdk_dependencies ${dependencies})
      endif()
    endforeach()
    list(REMOVE_ITEM sdk_dependencies ${ALPS_RUNTIME_TARGETS})
    list(REMOVE_DUPLICATES sdk_dependencies)
    if(sdk_dependencies)
      target_link_libraries(pyalps::runtime INTERFACE ${sdk_dependencies})
    endif()
  endif()
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    # CMake derives build RPATHs from the imported libraries. DT_RPATH also
    # resolves their transitive dependencies, such as libgfortran.
    target_link_options(pyalps::runtime INTERFACE "LINKER:--disable-new-dtags")
  endif()
endblock()
