# Copyright (C) 2026 ALPS Collaboration. SPDX-License-Identifier: MIT
# Diagonalization is deterministic and runs to completion, so it has no
# execution settings. Each conserved quantum-number sector is diagonalized
# separately.
# A single momentum sector, e.g. "0" or "3.14159 0"; by default all momenta.
[parameters.TOTAL_MOMENTUM]
type = "string"
[parameters.TRANSLATION_SYMMETRY]
type = "bool"
default = true
# Complex arithmetic; chosen by default when Bloch states are used.
[parameters.COMPLEX]
type = "bool"
[parameters.PRINT_EIGENVECTORS]
type = "bool"
default = false
[parameters.MEASURE_ENERGY]
type = "bool"
default = true
