/*****************************************************************************
*
* Tutorial: How to ALPSize your applications
*
* Copyright (C) 2005-2010 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#pragma once
#include "wolff_schema.hpp"
#include <alps/alea.hpp>
#include <alps/alea/hdf5.hpp>
#include <alps/run_config.hpp>
#include <alps/hdf5/vector.hpp>
#include <numeric>
#include <boost/random.hpp>
#include <array>
#include <chrono>
#include <climits>
#include <cmath>
#include <iostream>
#include <stack>
#include <vector>

// Both lessons sample H = -sum_b s_i*s_j with unit ferromagnetic bonds.
// Keeping a joint sample is essential for the Binder ratio's uncertainty.
class wolff_chain {
public:
    wolff_chain(std::vector<std::vector<int>> neighbors, double temperature)
        : neighbors_(std::move(neighbors)), spins_(neighbors_.size(), 1),
          magnetization_(spins_.size()), probability_(-std::expm1(-2/temperature)) {}
    template<class Random> std::vector<double> step(Random& random) {
        const int first = int(random()*spins_.size()), old = spins_[first];
        spins_[first] = -old;
        std::stack<int> pending;
        pending.push(first);
        int size = 0;
        while (!pending.empty()) {
            ++size;
            const int site = pending.top();
            pending.pop();
            for (int neighbor : neighbors_[site])
                if (spins_[neighbor] == old && random() < probability_) {
                    pending.push(neighbor);
                    spins_[neighbor] = -old;
                }
        }
        magnetization_ -= 2*old*size;
        return sample();
    }
    std::vector<double> sample() const {
        const double m = magnetization_/double(spins_.size());
        return {m, m*m, m*m*m*m};
    }
    void save(alps::hdf5::archive& ar) const {
        ar["checkpoint/spins"] << spins_;
        ar["checkpoint/neighbors"] << topology();
    }
    void load(alps::hdf5::archive& ar) {
        std::vector<int> spins;
        std::vector<uint64_t> neighbors;
        ar["checkpoint/spins"] >> spins;
        ar["checkpoint/neighbors"] >> neighbors;
        if (spins.size()!=spins_.size() || neighbors!=topology()
                || !std::all_of(spins.begin(), spins.end(), [](int s) { return s==1 || s==-1; }))
            throw std::invalid_argument("Checkpoint spins or lattice differ from this run");
        spins_ = std::move(spins);
        magnetization_ = std::accumulate(spins_.begin(), spins_.end(), 0);
    }
private:
    std::vector<uint64_t> topology() const {
        std::vector<uint64_t> data;
        for (auto const& neighbors : neighbors_) {
            data.push_back(neighbors.size());
            data.insert(data.end(), neighbors.begin(), neighbors.end());
        }
        return data;
    }
    std::vector<std::vector<int>> neighbors_;
    std::vector<int> spins_;
    int magnetization_;
    double probability_;
};

struct binder_ratio : alps::alea::transformer<double> {
    size_t in_size() const override { return 3; }
    size_t out_size() const override { return 1; }
    alps::alea::column<double> operator()(alps::alea::column<double> const& x) const override {
        if (!(x(2)>0)) throw std::domain_error("Binder ratio needs positive <m^4> in every jackknife sample");
        return alps::alea::column<double>{x(1)*x(1)/x(2)};
    }
};

inline const std::array<std::string,3> wolff_names{"Magnetization", "Magnetization^2", "Magnetization^4"};
inline void write_wolff_results(alps::hdf5::archive& archive, alps::alea::batch_result<double> const& joint) {
    auto const& names = wolff_names;
    alps::alea::hdf5_serializer raw(archive, "/simulation"), results(archive, "/simulation/results");
    serialize(raw, "joint", joint);
    if (!(joint.observations()>1)) {
        archive.create_group("/simulation/results");
        archive["/simulation/unavailable/Statistics"] << std::string("At least two effective batches are required");
        return;
    }
    for (size_t j=0; j<3; ++j) {
        Eigen::Matrix<double,1,3> select = Eigen::Matrix<double,1,3>::Zero(); select(j)=1;
        auto result = alps::alea::transform(alps::alea::jackknife_prop(),
            alps::alea::linear_transformer<double>(select), joint);
        const auto key = archive.encode_segment(names[j]);
        serialize(results, key, result);
        std::cout << names[j] << ": " << result.mean()(0) << " +/- " << result.stderror()(0);
        std::cout << '\n';
    }
    const std::string name = "Binder Ratio of Magnetization";
    try {
        auto result = alps::alea::transform(alps::alea::jackknife_prop(), binder_ratio(), joint);
        serialize(results, name, result);
        std::cout << name << ": " << result.mean()(0) << " +/- " << result.stderror()(0) << '\n';
    } catch (std::domain_error const& error) {
        archive["/simulation/unavailable/"+name] << std::string(error.what());
    }
}

template<class Lattice>
int wolff_main(int argc, char** argv, Lattice lattice, bool model_parameters=false) {
    try {
        bool validate = false;
        std::string file;
        for (int i=1; i<argc; ++i) {
            const std::string argument(argv[i]);
            if (argument == "--schema") { std::cout << wolff_schema; return 0; }
            if (argument == "--help" || argument == "-h") {
                std::cout << "Usage: wolff [--validate] run.toml | wolff --schema\n";
                return 0;
            }
            if (argument == "--validate") { validate = true; continue; }
            if (argument.empty() || argument.front() == '-' || !file.empty())
                throw std::invalid_argument("Expected one TOML run file");
            file = argument;
        }
        if (file.empty()) throw std::invalid_argument("Expected one TOML run file");
        const auto schema = model_parameters ? alps::extend_run_schema(file, wolff_schema) : std::string(wolff_schema);
        auto run = alps::load_run_configuration(file, schema);
        if (!run.parameters.exists("THERMALIZATION"))
            run.parameters["THERMALIZATION"] = run.parameters["SWEEPS"].template as<int64_t>()/8;
        const double temperature = run.parameters["T"].template as<double>();
        const auto bins = run.execution["bins"].template as<size_t>();
        if (!(temperature>0) || bins%2) throw std::invalid_argument("T must be positive; bins must be even");
        auto neighbors = lattice(run);
        if (neighbors.empty() || neighbors.size()>size_t(INT_MAX/2))
            throw std::invalid_argument("Lattice site count is outside the supported range");
        if (validate) { std::cout << "Valid Wolff configuration\n"; return 0; }
        const auto started = std::chrono::steady_clock::now();
        wolff_chain chain(std::move(neighbors), temperature);
        boost::variate_generator<boost::mt19937, boost::uniform_real<>> random(
            boost::mt19937(run.execution["seed"].template as<int>()), boost::uniform_real<>());
        alps::alea::batch_acc<double> samples(3, bins);
        std::array<alps::alea::autocorr_acc<double>,3> diagnostics;
        for (int64_t i=0; i<run.parameters["THERMALIZATION"].template as<int64_t>(); ++i) chain.step(random);
        for (int64_t i=0; i<run.parameters["SWEEPS"].template as<int64_t>(); ++i) {
            auto values = chain.step(random);
            samples << alps::alea::make_adapter(values);
            for (size_t j=0; j<3; ++j) diagnostics[j] << alps::alea::make_adapter(values[j]);
        }
        const auto joint = samples.result();
        alps::hdf5::save_checkpoint(run.output["results"].template as<std::string>(), [&](auto& archive) {
            archive["/parameters"] << run.parameters;
            archive["/run_config"] << run;
            write_wolff_results(archive, joint);
            alps::alea::hdf5_serializer analysis(archive, "/simulation/realizations/0/clones/0/autocorrelation");
            for (size_t j=0; j<3; ++j) {
                const auto result = diagnostics[j].result();
                serialize(analysis, archive.encode_segment(wolff_names[j]), result);
                if (result.tau_available()) std::cout << wolff_names[j] << " tau: " << result.tau()(0) << '\n';
            }
        });
        std::cerr << "Elapsed time = " << std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count() << " sec\n";
        return 0;
    } catch (std::exception const& error) { std::cerr << error.what() << '\n'; return 1; }
}
