# Copyright (C) 2026 ALPS Collaboration. SPDX-License-Identifier: MIT
schema_version = 1
[parameters.LATTICE]
type = "string"
[parameters.GRAPH]
type = "string"
[parameters.MODEL]
type = "string"
required = true
# Conserved quantum numbers, e.g. "N,Sz".
[parameters.CONSERVED_QUANTUMNUMBERS]
type = "string"
[input.lattice_library]
type = "path"
[input.model_library]
type = "path"
[output.results]
type = "path"
required = true
[execution]
