#pragma once
// GENERATED by contributions/harness/generate.py from manifest.yml. Do not edit.

#include "problem.hpp"
#include "solver.hpp"

#include <algorithm>
#include <cmath>
#include <memory>
#include <optional>
#include <vector>

// Contract dense_eigenvalues: all eigenvalues of the symmetric n x n row-major
// matrix h, in any order.
std::vector<double> jacobi_eigenvalues(std::vector<double> h, int n);

namespace onboard {

class Algorithm final : public Solver {
public:
    explicit Algorithm(const MatrixProblem& p) : p_(p) {}

    std::optional<Estimate> groundStateEnergy() const override {
        const int n = p_.numSites();
        std::vector<double> levels = jacobi_eigenvalues(p_.singleParticleMatrix(), n);
        if (static_cast<int>(levels.size()) != n) return std::nullopt;
        std::sort(levels.begin(), levels.end());

        double e = 0.0;
        for (int k = 0; k < p_.numParticles(); ++k) e += levels[k];
        if (!std::isfinite(e)) return std::nullopt;
        return Estimate{e};
    }

    const char* name() const override { return "jacobi_ed"; }

private:
    const MatrixProblem& p_;
};

inline std::unique_ptr<const Solver> makeAlgorithm(const MatrixProblem& p) {
    return std::make_unique<Algorithm>(p);
}

} // namespace onboard
