application = "heatbath-ising"
schema_version = 1
[parameters.ALGORITHM]
type = "string"
default = "ising"
choices = ["ising", "ising; temperature scan"]
[parameters.NUM_TEMPERATURES]
type = "int64"
min = 1
max = 10000
[parameters.INITIAL_TEMPERATURE]
type = "float64"
[parameters.DIFF_TEMPERATURE]
type = "float64"
[parameters.INITIAL_THERMALIZATION]
type = "int64"
min = 0
