#  Copyright Matthias Troyer and Synge Todo 2009 - 2010.
#   Permission is hereby granted, free of charge, to any person obtaining
#   a copy of this software and associated documentation files (the “Software”),
#   to deal in the Software without restriction, including without limitation
#   the rights to use, copy, modify, merge, publish, distribute, sublicense,
#   and/or sell copies of the Software, and to permit persons to whom the
#   Software is furnished to do so, subject to the following conditions:
#  
#   The above copyright notice and this permission notice shall be included
#   in all copies or substantial portions of the Software.
#  
#   THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS
#   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#   DEALINGS IN THE SOFTWARE.

configure_file(xdrdump2.input.cmake ${CMAKE_CURRENT_BINARY_DIR}/boostdump2.input)
configure_file(xdrdump2.input.cmake ${CMAKE_CURRENT_BINARY_DIR}/xdrdump2.input)

foreach(
  name
  os
  sizeof
  xdrdump
  xdrdump2
  boostdump
  boostdump2
  boostdump3
  boostdump4)
  add_executable(${name} ${name}.C)

  target_link_libraries(${name} PRIVATE ALPS::osiris)
  alps_add_test(${name})
  set_property(TEST ${name} PROPERTY LABELS osiris)
endforeach()

target_link_libraries(os PRIVATE ALPS::utilities)

add_executable(osiris_comm_contract comm_contract.cpp)
target_link_libraries(osiris_comm_contract PRIVATE ALPS::osiris)
alps_add_test(osiris_comm_contract)
set_property(TEST osiris_comm_contract PROPERTY LABELS osiris)
