# SPDX-License-Identifier: MIT
string(RANDOM LENGTH 12 nonce)
set(work "${CMAKE_CURRENT_BINARY_DIR}/scheduler-${runtime}-${nonce}")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/job.in.xml" "<JOB><INPUT file=\"job.in.xml\"/><OUTPUT file=\"job.out.xml\"/><TASK status=\"new\"><INPUT file=\"task.in.xml\"/><OUTPUT file=\"task.out.xml\"/></TASK></JOB>")
file(WRITE "${work}/task.in.xml" "<SIMULATION><PARAMETERS><PARAMETER name=\"ALGORITHM\">test</PARAMETER><PARAMETER name=\"SEED\">42</PARAMETER><PARAMETER name=\"NUM_CLONES\">1</PARAMETER></PARAMETERS></SIMULATION>")

function(run expected)
  execute_process(COMMAND ${launcher} "${program}" "${runtime}" ${ARGN}
    WORKING_DIRECTORY "${work}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors
    TIMEOUT 30)
  if(NOT "${result}" STREQUAL "${expected}")
    message(FATAL_ERROR "Scheduler ${runtime}: expected ${expected}, got ${result}\n${output}\n${errors}")
  endif()
endfunction()

run(0 --help)
if(NOT launcher)
  run(0 --invalid-option)
  run(0 missing.xml)
endif()
run(0 ${scheduler_options} --no-evaluate --dump-policy all job.in.xml)
file(READ "${work}/job.out.xml" result)
if(NOT result MATCHES "status=\"completed\"")
  message(FATAL_ERROR "Scheduler did not finish its task: ${result}")
endif()
file(GLOB checkpoints "${work}/*.h5")
if(NOT checkpoints)
  message(FATAL_ERROR "Scheduler did not save a checkpoint")
endif()
# A completed job must stay complete on restart, without dispatching another clone.
run(0 ${scheduler_options} --no-evaluate --dump-policy all job.out.xml)
file(READ "${work}/job.out.xml" restarted)
if(NOT restarted MATCHES "status=\"completed\"")
  message(FATAL_ERROR "Restart changed the completed task state: ${restarted}")
endif()
file(REMOVE_RECURSE "${work}")
