/*****************************************************************************
*
* Tutorial: How to ALPSize your applications
*
* Copyright (C) 2005-2010 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include <alps/run_config.hpp>
#include <iostream>

constexpr char hello_schema[] = R"toml(
application = "hello"
schema_version = 1
[parameters.WORLD]
type = "string"
required = true
[input]
[output]
[execution]
)toml";

int main(int argc, char** argv) {
    try {
        bool validate = false;
        std::string file;
        for (int i=1; i<argc; ++i) {
            const std::string argument(argv[i]);
            if (argument == "--schema") { std::cout << hello_schema; return 0; }
            if (argument == "--help" || argument == "-h") {
                std::cout << "Usage: hello [--validate] run.toml | hello --schema\n";
                return 0;
            }
            if (argument == "--validate") { validate = true; continue; }
            if (argument.empty() || argument.front() == '-' || !file.empty())
                throw std::invalid_argument("Expected one TOML run file");
            file = argument;
        }
        if (file.empty()) throw std::invalid_argument("Expected one TOML run file");
        const auto run = alps::load_run_configuration(file, hello_schema);
        if (validate) std::cout << "Valid hello configuration\n";
        else std::cout << "hello, " << run.parameters["WORLD"].as<std::string>() << '\n';
        return 0;
    } catch (std::exception const& error) {
        std::cerr << "hello: " << error.what() << '\n';
        return 1;
    }
}
