/*****************************************************************************
*
* Tutorial: How to ALPSize your applications
*
* Copyright (C) 2005-2010 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#pragma once
#include "../wolff.hpp"
#include <alps/mc/driver.hpp>
#include <alps/lattice.h>

class wolff_worker : public alps::mcbase {
public:
    wolff_worker(alps::params const& p, size_t bins, size_t chain)
        : mcbase(p, chain), chain_id_(chain), bins_(bins),
          warmup_(p["THERMALIZATION"].as<uint64_t>()), production_(p["SWEEPS"].as<uint64_t>()),
          state_(neighbors(p), p["T"].as<double>()) {
        if (!(p["T"].as<double>()>0) || production_>UINT64_MAX-warmup_)
            throw std::invalid_argument("Positive T and a representable sweep count are required");
        measurements.emplace("Moments", std::make_shared<alps::alea::batch_acc<double>>(3,bins));
        for (auto const& name : wolff_names)
            measurements.emplace(name, std::make_shared<alps::alea::autocorr_acc<double>>());
    }
    static alps::params checkpoint_parameters(alps::params p) { p.erase("SWEEPS"); return p; }
    uint64_t completed_sweeps() const { return sweeps_; }
    uint64_t measurement_count() const { return measurement("Moments")->count(); }
    double fraction_completed() const override {
        return sweeps_<=warmup_ ? 0. : double(sweeps_-warmup_)/production_;
    }
    void update() override {
        if (sweeps_>=warmup_+production_ || measurement_count()!=(sweeps_>warmup_ ? sweeps_-warmup_ : 0))
            throw std::logic_error("Complete each update/measure pair before advancing");
        state_.step(random); ++sweeps_;
    }
    void measure() override {
        if (sweeps_<=warmup_) return;
        if (measurement_count()!=sweeps_-warmup_-1) throw std::logic_error("Measure each update once");
        const auto values = state_.sample();
        *measurement("Moments") << alps::alea::make_adapter(values);
        for (size_t i=0; i<3; ++i)
            *measurement<alps::alea::autocorr_acc<double>>(wolff_names[i]) << alps::alea::make_adapter(values[i]);
    }
    alps::mc::batch_results collect_results() const { return {{"Moments",measurement("Moments")->result()}}; }
    void save(alps::hdf5::archive& ar) const override {
        if (measurement_count()!=(sweeps_>warmup_ ? sweeps_-warmup_ : 0))
            throw std::logic_error("Measure before checkpointing");
        mcbase::save(ar); state_.save(ar);
        ar["checkpoint/sweeps"] << sweeps_;
        ar["checkpoint/chain_id"] << uint64_t(chain_id_);
    }
    void load(alps::hdf5::archive& ar) override {
        alps::params saved;
        uint64_t sweeps, chain;
        ar["/parameters"] >> saved;
        ar["checkpoint/sweeps"] >> sweeps; ar["checkpoint/chain_id"] >> chain;
        if (checkpoint_parameters(saved)!=checkpoint_parameters(parameters) || chain!=chain_id_
                || sweeps>warmup_+production_) throw std::invalid_argument("Checkpoint does not match this run");
        auto state = state_; state.load(ar);
        alps::mc::validate_measurements(measurements, ar, sweeps>warmup_ ? sweeps-warmup_ : 0, bins_);
        auto invocation = parameters;
        mcbase::load(ar); parameters=std::move(invocation);
        state_=std::move(state); sweeps_=sweeps;
    }
private:
    static std::vector<std::vector<int>> neighbors(alps::params const& p) {
        alps::graph_helper<> graph(p);
        if (!graph.num_sites() || graph.num_sites()>size_t(INT_MAX/2))
            throw std::invalid_argument("Lattice site count is outside the supported range");
        std::vector<std::vector<int>> result(graph.num_sites());
        for (size_t i=0; i<result.size(); ++i)
            for (auto [it,end]=graph.neighbors(i); it!=end; ++it) result[i].push_back(*it);
        return result;
    }
    size_t chain_id_, bins_;
    uint64_t warmup_, production_, sweeps_=0;
    wolff_chain state_;
};
