/*****************************************************************************
*
* Tutorial: How to ALPSize your applications
*
* Copyright (C) 2005-2010 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include "wolff_worker.h"

int main(int argc, char** argv) {
    auto prepare = [](alps::params& p, alps::run_configuration const&) {
        if (!p.exists("THERMALIZATION")) p["THERMALIZATION"] = p["SWEEPS"].as<uint64_t>()/8;
    };
    auto publish = [](alps::run_configuration const& run, auto const& chains, alps::params const& p) {
        std::vector<alps::mc::batch_results> results;
        for (auto const& chain : chains) results.push_back(chain->collect_results());
        const auto joint = alps::mc::pool(results).at("Moments");
        alps::hdf5::save_checkpoint(run.output["results"].as<std::string>(), [&](auto& ar) {
            ar["/parameters"] << p; ar["/run_config"] << run;
            write_wolff_results(ar, joint);
            for (size_t id=0; id<chains.size(); ++id) {
                const auto path = "/simulation/realizations/0/clones/"+std::to_string(id);
                ar[path+"/completed_sweeps"] << chains[id]->completed_sweeps();
                alps::alea::hdf5_serializer codec(ar, path+"/autocorrelation");
                for (auto const& name : wolff_names)
                    serialize(codec, ar.encode_segment(name), chains[id]->template measurement<alps::alea::autocorr_acc<double>>(name)->result());
            }
        });
    };
    return alps::mc::main<wolff_worker>(argc, argv, "wolff", wolff_schema, {}, prepare, publish);
}
