# The build is the authoritative inventory of module-owned production files.
# Keep this manifest independent of Python so library-only consumers need only
# CMake and their C/C++ toolchain. The source audit runs with developer tests.
function(alps_json_array output)
  set(items "")
  foreach(value IN LISTS ARGN)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    list(APPEND items "\"${value}\"")
  endforeach()
  list(JOIN items "," json)
  set(${output} "[${json}]" PARENT_SCOPE)
endfunction()

function(alps_relative_files output)
  set(files "")
  foreach(path IN LISTS ARGN)
    if(NOT IS_ABSOLUTE "${path}")
      set(path "${CMAKE_CURRENT_SOURCE_DIR}/${path}")
    endif()
    cmake_path(NORMAL_PATH path)
    file(RELATIVE_PATH path "${PROJECT_SOURCE_DIR}" "${path}")
    list(APPEND files "${path}")
  endforeach()
  list(REMOVE_DUPLICATES files)
  list(SORT files)
  alps_json_array(json ${files})
  set(${output} "${json}" PARENT_SCOPE)
endfunction()

function(alps_register_module)
  cmake_parse_arguments(PARSE_ARGV 0 module "" "NAME;ROOT;HEADER_SET;DEBT_FILE"
    "TARGETS;HEADER_TARGETS;PRIVATE_FILES;EXTRA_FILES;DEPENDS;GENERATED_HEADERS")
  if(NOT module_NAME OR module_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Invalid ALPS module registration: ${module_UNPARSED_ARGUMENTS}")
  endif()
  if(NOT module_ROOT)
    set(module_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()
  set(public_headers "")
  set(include_roots "")
  if(module_HEADER_SET)
    if(NOT module_HEADER_TARGETS)
      set(module_HEADER_TARGETS alps_headers)
    endif()
    foreach(target IN LISTS module_HEADER_TARGETS)
      get_target_property(headers ${target} HEADER_SET_${module_HEADER_SET})
      get_target_property(roots ${target} HEADER_DIRS_${module_HEADER_SET})
      list(APPEND public_headers ${headers})
      list(APPEND include_roots ${roots})
    endforeach()
  endif()
  set(private_files ${module_PRIVATE_FILES} ${module_EXTRA_FILES})
  foreach(target IN LISTS module_TARGETS)
    get_target_property(sources ${target} SOURCES)
    get_target_property(source_dir ${target} SOURCE_DIR)
    foreach(source IN LISTS sources)
      if(source MATCHES "^\\$<")
        continue()
      endif()
      if(NOT IS_ABSOLUTE "${source}")
        set(source "${source_dir}/${source}")
      endif()
      cmake_path(IS_PREFIX module_ROOT "${source}" NORMALIZE owned)
      if(owned)
        list(APPEND private_files "${source}")
      endif()
    endforeach()
  endforeach()
  set(test_roots "")
  if(IS_DIRECTORY "${module_ROOT}/tests")
    list(APPEND test_roots "${module_ROOT}/tests")
  endif()
  alps_relative_files(headers_json ${public_headers})
  alps_relative_files(includes_json ${include_roots})
  alps_relative_files(private_json ${private_files})
  alps_relative_files(tests_json ${test_roots})
  alps_json_array(depends_json ${module_DEPENDS})
  alps_json_array(generated_json ${module_GENERATED_HEADERS})
  file(RELATIVE_PATH module_root "${PROJECT_SOURCE_DIR}" "${module_ROOT}")
  set(debt_json "[]")
  if(module_DEBT_FILE)
    file(READ "${CMAKE_CURRENT_SOURCE_DIR}/${module_DEBT_FILE}" debt_json)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${module_DEBT_FILE}")
  endif()
  set(json "{\"name\":\"${module_NAME}\",\"root\":\"${module_root}\",\"public_include_roots\":${includes_json},\"public_headers\":${headers_json},\"private_files\":${private_json},\"test_roots\":${tests_json},\"depends\":${depends_json},\"generated_headers\":${generated_json},\"allowed_unresolved\":${debt_json}}")
  get_property(names GLOBAL PROPERTY ALPS_MODULE_NAMES)
  if(module_NAME IN_LIST names)
    message(FATAL_ERROR "Duplicate ALPS module registration: ${module_NAME}")
  endif()
  set_property(GLOBAL APPEND PROPERTY ALPS_MODULE_NAMES "${module_NAME}")
  # Store each object separately: JSON debt explanations may contain semicolons,
  # which must not be interpreted as CMake list separators.
  set_property(GLOBAL PROPERTY ALPS_MODULE_ENTRY_${module_NAME} "${json}")
endfunction()

function(alps_write_module_manifest)
  get_property(names GLOBAL PROPERTY ALPS_MODULE_NAMES)
  set(entries "")
  set(separator "")
  foreach(name IN LISTS names)
    get_property(entry GLOBAL PROPERTY ALPS_MODULE_ENTRY_${name})
    string(APPEND entries "${separator}${entry}")
    set(separator ",\n")
  endforeach()
  alps_json_array(root_json "${PROJECT_SOURCE_DIR}")
  string(JSON root_json GET "${root_json}" 0)
  # CMake paths use forward slashes on every platform.
  string(REPLACE "\"" "\\\"" root_json "${root_json}")
  set(manifest "${PROJECT_BINARY_DIR}/alps-module-manifest.json")
  file(WRITE "${manifest}" "{\"schema_version\":1,\"source_root\":\"${root_json}\",\"modules\":[\n${entries}\n]}\n")
  if(ALPS_BUILD_TESTING)
    find_package(Python 3.11 REQUIRED COMPONENTS Interpreter)
    add_test(NAME module_architecture
      COMMAND "${Python_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/.github/scripts/check_module_architecture.py"
        --manifest "${manifest}" --write-report "${PROJECT_BINARY_DIR}/alps-module-architecture.json")
    set_tests_properties(module_architecture PROPERTIES LABELS architecture)
  endif()
endfunction()
