#  Copyright Matthias Troyer 2009 - 2010.
#   Permission is hereby granted, free of charge, to any person obtaining
#   a copy of this software and associated documentation files (the “Software”),
#   to deal in the Software without restriction, including without limitation
#   the rights to use, copy, modify, merge, publish, distribute, sublicense,
#   and/or sell copies of the Software, and to permit persons to whom the
#   Software is furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included
#   in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS
#   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#   DEALINGS IN THE SOFTWARE.

add_executable(loop loop.C loop_custom.C loop_model.C)
target_include_directories(loop PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(loop PRIVATE ALPS::alps)
alps_native_qmc(loop)
alps_install_applications(loop)

if(ALPS_BUILD_TESTING)
  add_executable(loop_temperature_grid tests/temperature_grid.cpp)
  target_link_libraries(loop_temperature_grid PRIVATE ALPS::params)
  alps_add_test(loop_temperature_grid)
  set_tests_properties(loop_temperature_grid PROPERTIES LABELS "qmc")
endif()
