# Copyright (C) 2026 ALPS Collaboration. SPDX-License-Identifier: MIT
[parameters.ALGORITHM]
type = "string"
default = "loop"
choices = ["loop", "loop; path integral", "loop; sse", "loop; exchange", "loop; path integral; exchange", "loop; sse; exchange"]
[parameters.DISABLE_IMPROVED_ESTIMATOR]
type = "bool"
default = false
