# SPDX-License-Identifier: MIT
string(RANDOM LENGTH 12 nonce)
set(work "${CMAKE_CURRENT_BINARY_DIR}/loop-${nonce}")
# Seeded observables recorded before extracting the worker and distribution.
foreach(case "sse|sse|0.5|0|0|-0.6094" "pi|path integral|0.5|0|0|-0.6445"
             "sse1|sse|1|0|0|-4.6133" "pi1|path integral|1|0|0|-4.5312"
             "field|path integral|0.5|0.3|1|-0.7152" "normal|sse|0.5|0|1|-0.6094")
  string(REPLACE "|" ";" values "${case}")
  list(GET values 0 name)
  list(GET values 1 algorithm)
  list(GET values 2 spin)
  list(GET values 3 field)
  list(GET values 4 disable)
  list(GET values 5 energy)
  set(dir "${work}/${name}")
  file(MAKE_DIRECTORY "${dir}")
  file(WRITE "${dir}/job.in.xml" "<JOB><INPUT file=\"job.in.xml\"/><OUTPUT file=\"job.out.xml\"/><TASK status=\"new\"><INPUT file=\"task.in.xml\"/><OUTPUT file=\"task.out.xml\"/></TASK></JOB>")
  set(parameters "")
  foreach(pair "LATTICE|chain lattice" "MODEL|spin" "ALGORITHM|loop; ${algorithm}" "L|4" "J|1" "T|1"
               "local_S|${spin}" "h|${field}" "SWEEPS|256" "THERMALIZATION|32" "SEED|42" "DISORDER_SEED|17"
               "LATTICE_LIBRARY|${resources}/lattices.xml" "MODEL_LIBRARY|${resources}/models.xml")
    string(FIND "${pair}" "|" separator)
    string(SUBSTRING "${pair}" 0 ${separator} key)
    math(EXPR separator "${separator}+1")
    string(SUBSTRING "${pair}" ${separator} -1 value)
    string(APPEND parameters "<PARAMETER name=\"${key}\">${value}</PARAMETER>")
  endforeach()
  if(disable)
    string(APPEND parameters "<PARAMETER name=\"DISABLE_IMPROVED_ESTIMATOR\">1</PARAMETER>")
  endif()
  file(WRITE "${dir}/task.in.xml" "<SIMULATION><PARAMETERS>${parameters}</PARAMETERS></SIMULATION>")
  execute_process(COMMAND "${program}" --write-xml --dump-policy all job.in.xml
    WORKING_DIRECTORY "${dir}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
  if(NOT status EQUAL 0 OR NOT EXISTS "${dir}/task.out.xml")
    message(FATAL_ERROR "${name} failed: ${output}\n${errors}")
  endif()
  file(READ "${dir}/task.out.xml" result)
  string(REGEX MATCH "<SCALAR_AVERAGE name=\"Energy\">[^<]*<COUNT>[^<]*</COUNT>[^<]*<MEAN[^>]*>([^<]*)</MEAN>" match "${result}")
  string(STRIP "${CMAKE_MATCH_1}" actual)
  if(NOT actual STREQUAL energy)
    message(FATAL_ERROR "${name} energy changed: expected ${energy}, got ${actual}")
  endif()
endforeach()
file(REMOVE_RECURSE "${work}")
