// SPDX-License-Identifier: MIT
#pragma once
#include <gtest/gtest.h>
#include <algorithm>
#include <initializer_list>
#include <sstream>
#include <utility>
#include <vector>

// Canonical labels have a stable discrete encoding. These expectations were
// extracted from the historical fixtures, not regenerated by the algorithm.
template<class Label> void expect_label_encoding(const Label& label, const char* expected) {
    std::ostringstream encoded;
    encoded << label;
    EXPECT_EQ(encoded.str(), expected);
}

template<class Partition> void expect_partition(const Partition& actual,
    std::initializer_list<std::initializer_list<std::size_t>> expected) {
    ASSERT_EQ(actual.size(), expected.size());
    auto group = actual.begin();
    for (const auto& reference : expected) {
        const std::vector<std::size_t> values(group->begin(), group->end());
        EXPECT_EQ(values, std::vector<std::size_t>(reference));
        ++group;
    }
}

template<class Map> void expect_color_mapping(const Map& actual,
    std::initializer_list<std::pair<unsigned, unsigned>> expected) {
    std::vector<std::pair<unsigned, unsigned>> values;
    for (const auto& entry : actual) values.emplace_back(entry.first, entry.second);
    EXPECT_EQ(values, (std::vector<std::pair<unsigned, unsigned>>(expected)));
}

template<class Ordering> void expect_vertex_permutation(const Ordering& ordering, std::size_t vertices) {
    ASSERT_EQ(ordering.size(), vertices);
    std::vector<std::size_t> sorted(ordering.begin(), ordering.end());
    std::sort(sorted.begin(), sorted.end());
    for (std::size_t vertex = 0; vertex < vertices; ++vertex) EXPECT_EQ(sorted[vertex], vertex);
}
