[parameters]
LATTICE = "simple cubic lattice"
MODEL = "spin"
local_S = 0.5
L = 6
J = 1.0
CUTOFF = 1000
[execution]
seed = 42
[output]
results = "parm6d-L6.out.h5"
checkpoint = "parm6d-L6.checkpoint.h5"
